version: "3.2"

services:
  whirlpool:
    image: "samouraiwallet/dojo-whirlpool:${DOJO_WHIRLPOOL_VERSION_TAG}"
    container_name: whirlpool
    build:
      context: ./whirlpool
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-whirlpool.conf
    restart: always
    command: /restart.sh
    expose:
      - "8898"
    volumes:
      - data-whirlpool:/home/whirlpool
    networks:
      whirlnet:
        ipv4_address: 172.30.1.8

volumes:
  data-whirlpool:
