version: "3.2"

services:
  db:
    image: "samouraiwallet/dojo-db:${DOJO_DB_VERSION_TAG}"
    container_name: db
    build:
      context: ./../..
      dockerfile: ./docker/my-dojo/mysql/Dockerfile
    env_file:
      - ./.env
      - ./conf/docker-mysql.conf
    restart: on-failure
    expose:
      - "3306"
    volumes:
      - data-mysql:/var/lib/mysql
    networks:
      dojonet:
        ipv4_address: 172.28.1.1

  node:
    image: "samouraiwallet/dojo-nodejs:${DOJO_NODEJS_VERSION_TAG}"
    container_name: nodejs
    build:
      context: ./../..
      dockerfile: ./docker/my-dojo/node/Dockerfile
    env_file:
      - ./.env
      - ./conf/docker-common.conf
      - ./conf/docker-mysql.conf
      - ./conf/docker-bitcoind.conf
      - ./conf/docker-node.conf
    restart: on-failure
    command: "/home/node/app/wait-for-it.sh db:3306 --timeout=360 --strict -- /home/node/app/restart.sh"
    expose:
      - "8080"
      - "8081"
      - "8082"
    volumes:
      - data-nodejs:/data
    depends_on:
      - db
    networks:
      dojonet:
        ipv4_address: 172.28.1.2

  nginx:
    image: "samouraiwallet/dojo-nginx:${DOJO_NGINX_VERSION_TAG}"
    container_name: nginx
    build:
      context: ./nginx
    env_file:
      - ./.env
      - ./conf/docker-common.conf
    restart: on-failure
    command: "/wait-for node:8080 --timeout=360 -- nginx"
    expose:
      - "80"
    volumes:
      - data-nginx:/data
    depends_on:
      - node
    networks:
      dmznet:
        ipv4_address: 172.29.1.3
      dojonet:
        ipv4_address: 172.28.1.3

  tor:
    image: "samouraiwallet/dojo-tor:${DOJO_TOR_VERSION_TAG}"
    container_name: tor
    build:
      context: ./tor
    env_file:
      - ./.env
      - ./conf/docker-tor.conf
    restart: on-failure
    command: /restart.sh
    volumes:
      - data-tor:/var/lib/tor
    networks:
      dmznet:
        ipv4_address: 172.29.1.4
      dojonet:
        ipv4_address: 172.28.1.4

networks:
  dojonet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
  dmznet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/16

volumes:
  data-mysql:
  data-nodejs:
  data-nginx:
  data-tor:
